title: Cat Connolly
email: revcatconnolly@gmail.com
description: >-
  Episcopal priest, preacher, pastor, and writer.
baseurl: ""
url: "https://catconnolly.com"

collections:
  writings:
    output: true

defaults:
  - scope:
      path: ""
      type: writings
    values:
      layout: writing
      nav_section: writings

plugins:
  - jekyll-feed

exclude:
  - docs/
